{
  flights(from: "ARN", to: "AKL", outDate: "20190808") {
    outboundFlights {
      startTimeInLocal
      endTimeInLocal
      stops
      originCity {
        name
        code
      }
      origin {
        name
        code
      }
      destination {
        name
      }
      via {
        name
      }
      connectionDuration
    }
    inboundFlights {
      origin {
        name
      }
    }
  }
}
