{
  flights(from: "ARN", to: "AKL", date: "20190808", adt: 2) {
    startTimeInLocal
    endTimeInLocal
    stops
    originCity {
      name
      code
    }
    origin {
      name
      code
    }
    destination {
      name
    }
    via {
      name
    }
    connectionDuration
  }
}
